from .chronoepilogi import ChronoEpilogi

try:
    from ._version import version as __version__
except ImportError:
    # _version.py is generated by hatch-vcs at build/install time; it won't
    # exist when running directly from an uninstalled source checkout.
    __version__ = "unknown"